name:                servant-flow
version:             0.1.0.0
github:              "henrylabs/servant-flow"
license:             BSD3
author:              "Tommy Engström"
maintainer:          "tommy@hihenry.com"
copyright:           "2018 Henry Labs"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tommyengstrom/servant-flow#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- containers
- lens
- servant
- servant-foreign
- text
- time
- unordered-containers
- mtl
- transformers
- http-types

default-extensions:
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- OverloadedStrings
- ScopedTypeVariables
- TypeApplications
- TypeSynonymInstances
- TypeOperators
- DataKinds
- DeriveGeneric

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  servant-flow-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-flow

tests:
  servant-flow-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-flow
    - servant-server
    - hspec
